
// Automatically generated by generate-breakages.ts; do not edit.
import { SchemaChange_Breakage } from "../capnp/schema-diff.ts";

export type OneOfBreakages = {
  unsupported: typeof SchemaChange_Breakage.WIRE,
  nodeAdded: typeof SchemaChange_Breakage.NONE,
  nodeRemoved: typeof SchemaChange_Breakage.WIRE | typeof SchemaChange_Breakage.CODE,
  nodeRenamed: typeof SchemaChange_Breakage.CODE,
  nodeIdChanged: typeof SchemaChange_Breakage.WIRE,
  memberOrdinalChanged: typeof SchemaChange_Breakage.WIRE,
  nodeTypeChanged: typeof SchemaChange_Breakage.WIRE | typeof SchemaChange_Breakage.CODE,
  fieldDefaultValueChanged: typeof SchemaChange_Breakage.WIRE,
  constValueChanged: typeof SchemaChange_Breakage.CODE,
  annotationTargetAdded: typeof SchemaChange_Breakage.NONE,
  annotationTargetRemoved: typeof SchemaChange_Breakage.CODE,
};
